version: '3'
services:
    serviio:
#        image: dnichyparuk/docker-serviio
        image: lsiocommunity/serviio
        container_name: serviio
        network_mode: "host"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/serviio/config:/config
            - /media/nas/transcode/serviio:/transcode
            - /media/nas/transmission/complete:/media/Completed
            - /media/nas/video:/media/video
            - /media/nas/music:/media/music
            - /media/nas/photo:/media/photo
            - /docker/serviio/logs:/opt/serviio/log
        restart: always
#        devices:
#            - /dev/dri:/dev/dri
#        ports:
#            - 23423:23423/tcp
#            - 23424:23424/tcp
#            - 8780:8780/tcp
#            - 8895:8895/tcp
#            - 1900:1900/udp
        privileged: true
        environment:
#            - VERSION=latest
            - TZ=Europe/Minsk
            - PGID=1000
            - PUID=1000
#            - NVIDIA_VISIBLE_DEVICES=all
#            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
