version: '3'
services:
    unifi:
        image: linuxserver/unifi
        container_name: unifi
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/unifi:/config
        ports:
            - 8080:8080
            - 8081:8081
            - 8443:8443
            - 8843:8843
            - 8880:8880
            - 3478:3478/udp
            - 6789:6789
            - 10001:10001
        restart: always
        environment:
            - PGID=1000
            - PUID=1000
            - TZ=Europe/Minsk  
